service: content-generator-server
app: content-generator
org: monthem
useDotenv: true
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  profile: serverless
  stage: dev
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action: 
            - "s3:ListBucket"
            - "s3:CreateBucket"
            - "s3:PutObject"
            - "s3:DeleteObject"
            - "s3:GetObject"
          Resource: arn:aws:s3:::msg-tmp-bucket

environment:
functions:
  main:
    handler: lambda.handler
    environment:
      # CUSTOM_CHROME: true
